from core.compare_face import CompareFace
from services.recognition_service import RecognitionService
from services.verification_service import VerificationService
from services.detection_service import DetectionService